### ISSUE TITLE
setCategoryIds

### ISSUE THREAD

**Issue by pborgesalves** [Afrozaar/wp-api-v2-client-java#32]
Hi,

I'm trying to assign categories to posts but is always assigned to Uncategorized.

Post post = new Post();
post.setTitle(aTitle().withRendered(title).build());
post.setExcerpt(anExcerpt().withRendered(excerpt).build());
post.setContent(aContent().withRendered(content).build());
        
List<Long> list = new ArrayList();
list.add(155L);
post.setCategoryIds(list);
client.createPost(post, PostStatus.publish);

Is there something wrong with my code?

Thank you

**Comment by johanmynhardt** [comment]
Hello @pborgesalves :)

Thank you for your feedback. This is indeed a bug that is not yet covered as we are currently using the library for mostly gathering data from WP. We are currently creating most of our content using the XML-RPC API.

There is definitely future plans to replace all our create calls with the REST-API, and since we have most of the other fields covered, I will create a test case and fix this for you shortly :)

**Comment by johanmynhardt** [comment]
@pborgesalves, I have released 2.0-beta15.2.01 and should be available via maven central in a while (I don't know how long this usually takes, but the release is complete, https://oss.sonatype.org/#nexus-search;quick~wp-api-v2-client-java)

**Comment by pborgesalves** [comment]
Thank you very much, @johanmynhardt

**Comment by johanmynhardt** [comment]
Hi @pborgesalves 

Please can you confirm that this is now working as you expect? If so, I can close this issue. 

Thanks :)

**Comment by pborgesalves** [comment]
Hi @johanmynhardt 
It's working. Thank you for your support.
